# Code generated by SdkContractGenerator. DO NOT EDIT.

CONTRACT = {
    "edit-image": {
        "models": ["ideogram-v3-character-edit", "ideogram-v3-edit"],
        "fields_by_model": {
            "ideogram-v3-character-edit": {
                "output_count": {
                    "enum": [1, 2, 3, 4],
                    "type": "integer"
                },
                "rendering_speed": {
                    "enum": ["turbo", "balanced", "quality"]
                },
                "seed": {
                    "type": "integer"
                },
                "source_image_url": {
                    "required": True
                },
                "style": {
                    "enum": ["auto", "realistic", "fiction"]
                }
            },
            "ideogram-v3-edit": {
                "output_count": {
                    "enum": [1, 2, 3, 4],
                    "type": "integer"
                },
                "rendering_speed": {
                    "enum": ["turbo", "balanced", "quality"]
                },
                "seed": {
                    "type": "integer"
                },
                "source_image_url": {
                    "required": True
                }
            }
        }
    },
    "reframe-image": {
        "models": ["ideogram-v3-reframe"],
        "fields_by_model": {
            "ideogram-v3-reframe": {
                "aspect_ratio": {
                    "enum": ["1:1", "3:4", "9:16", "4:3", "16:9"]
                },
                "output_count": {
                    "enum": [1, 2, 3, 4],
                    "type": "integer"
                },
                "rendering_speed": {
                    "enum": ["turbo", "balanced", "quality"]
                },
                "seed": {
                    "type": "integer"
                },
                "source_image_url": {
                    "required": True
                },
                "style": {
                    "enum": ["auto", "general", "realistic", "design"]
                }
            }
        }
    },
    "remix-image": {
        "models": ["ideogram-v3-character-remix", "ideogram-v3-remix"],
        "fields_by_model": {
            "ideogram-v3-character-remix": {
                "aspect_ratio": {
                    "enum": ["1:1", "3:4", "9:16", "4:3", "16:9"]
                },
                "output_count": {
                    "enum": [1, 2, 3, 4],
                    "type": "integer"
                },
                "rendering_speed": {
                    "enum": ["turbo", "balanced", "quality"]
                },
                "seed": {
                    "type": "integer"
                },
                "source_image_url": {
                    "required": True
                },
                "style": {
                    "enum": ["auto", "realistic", "fiction"]
                }
            },
            "ideogram-v3-remix": {
                "aspect_ratio": {
                    "enum": ["1:1", "3:4", "9:16", "4:3", "16:9"]
                },
                "output_count": {
                    "enum": [1, 2, 3, 4],
                    "type": "integer"
                },
                "rendering_speed": {
                    "enum": ["turbo", "balanced", "quality"]
                },
                "seed": {
                    "type": "integer"
                },
                "source_image_url": {
                    "required": True
                },
                "style": {
                    "enum": ["auto", "general", "realistic", "design"]
                }
            }
        }
    },
    "text-to-image": {
        "models": ["ideogram-v3-character", "ideogram-v3-text-to-image"],
        "fields_by_model": {
            "ideogram-v3-character": {
                "aspect_ratio": {
                    "enum": ["1:1", "3:4", "9:16", "4:3", "16:9"]
                },
                "output_count": {
                    "enum": [1, 2, 3, 4],
                    "type": "integer"
                },
                "rendering_speed": {
                    "enum": ["turbo", "balanced", "quality"]
                },
                "seed": {
                    "type": "integer"
                },
                "style": {
                    "enum": ["auto", "realistic", "fiction"]
                }
            },
            "ideogram-v3-text-to-image": {
                "aspect_ratio": {
                    "enum": ["1:1", "3:4", "9:16", "4:3", "16:9"]
                },
                "output_count": {
                    "enum": [1, 2, 3, 4],
                    "type": "integer"
                },
                "rendering_speed": {
                    "enum": ["turbo", "balanced", "quality"]
                },
                "seed": {
                    "type": "integer"
                },
                "style": {
                    "enum": ["auto", "general", "realistic", "design"]
                }
            }
        }
    }
}
